# Generated by Django 4.2.3 on 2023-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleado", "0002_rename_todo_empleado"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="estado",
            field=models.BooleanField(default=False),
        ),
    ]
