# Generated by Django 4.2.3 on 2023-07-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleado", "0004_remove_empleado_id_empleado_alter_empleado_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
